# Generated by Django 4.2.11 on 2024-03-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=255)),
                ('restaurant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_as_a', to='recommendations.restaurant')),
                ('restaurant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_as_b', to='recommendations.restaurant')),
            ],
            options={
                'unique_together': {('restaurant_a', 'restaurant_b', 'voter_id')},
            },
        ),
    ]
