# Generated by Django 4.2.11 on 2024-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_restaurant_address_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_curated',
            field=models.BooleanField(default=False),
        ),
    ]
